cmake_minimum_required(VERSION 3.16)

project(sdl-build)

macro(set_bool_default name value)
    set(${name} ${value} CACHE BOOL "")
endmacro()

macro(set_string_default name value)
    set(${name} "${value}" CACHE STRING "")
endmacro()

set_string_default(CMAKE_BUILD_TYPE Release)
set_bool_default(CMAKE_POSITION_INDEPENDENT_CODE ON)
set_bool_default(BUILD_SHARED_LIBS ON)

set_bool_default(SDL_SHARED ON)
set_bool_default(SDL_STATIC OFF)
set_bool_default(SDL_DEPS_SHARED ON)
set_bool_default(SDL_FRAMEWORK OFF)
set_bool_default(SDL_LIBC ON)
if(APPLE)
    set_bool_default(SDL_SYSTEM_ICONV OFF)
else()
    set_bool_default(SDL_SYSTEM_ICONV ON)
endif()
set_bool_default(SDL_LIBICONV OFF)
set_bool_default(SDL_GCC_ATOMICS ON)
set_bool_default(SDL_PTHREADS ON)
set_bool_default(SDL_PTHREADS_SEM ON)
set_bool_default(SDL_DLOPEN_NOTES ON)
set_string_default(SDL_ASSERTIONS auto)
set_string_default(SDL_VENDOR_INFO "")

set_bool_default(SDL_AUDIO ON)
set_bool_default(SDL_VIDEO ON)
set_bool_default(SDL_JOYSTICK ON)
set_bool_default(SDL_DIALOG ON)
set_bool_default(SDL_POWER ON)
set_bool_default(SDL_TRAY ON)
set_bool_default(SDL_RENDER OFF)
set_bool_default(SDL_GPU OFF)
set_bool_default(SDL_CAMERA OFF)
set_bool_default(SDL_HAPTIC OFF)
set_bool_default(SDL_HIDAPI ON)
set_bool_default(SDL_SENSOR OFF)

set_bool_default(SDL_DBUS OFF)
set_bool_default(SDL_LIBURING OFF)
set_bool_default(SDL_DISKAUDIO OFF)
set_bool_default(SDL_DUMMYAUDIO OFF)
set_bool_default(SDL_DUMMYVIDEO OFF)
set_bool_default(SDL_DUMMYCAMERA OFF)
set_bool_default(SDL_IBUS OFF)
set_bool_default(SDL_OPENGL ON)
set_bool_default(SDL_OPENGLES ON)
set_bool_default(SDL_OSS ON)
set_bool_default(SDL_ALSA ON)
set_bool_default(SDL_ALSA_SHARED ON)
set_bool_default(SDL_JACK ON)
set_bool_default(SDL_JACK_SHARED ON)
set_bool_default(SDL_PIPEWIRE ON)
set_bool_default(SDL_PIPEWIRE_SHARED ON)
set_bool_default(SDL_PULSEAUDIO ON)
set_bool_default(SDL_PULSEAUDIO_SHARED ON)
set_bool_default(SDL_SNDIO ON)
set_bool_default(SDL_SNDIO_SHARED ON)
set_bool_default(SDL_X11 ON)
set_bool_default(SDL_X11_SHARED ON)
set_bool_default(SDL_X11_XCURSOR OFF)
set_bool_default(SDL_X11_XDBE OFF)
set_bool_default(SDL_X11_XINPUT ON)
set_bool_default(SDL_X11_XFIXES OFF)
set_bool_default(SDL_X11_XRANDR ON)
set_bool_default(SDL_X11_XSCRNSAVER OFF)
set_bool_default(SDL_X11_XSHAPE OFF)
set_bool_default(SDL_X11_XSYNC OFF)
set_bool_default(SDL_X11_XTEST OFF)
set_bool_default(SDL_FRIBIDI OFF)
set_bool_default(SDL_FRIBIDI_SHARED OFF)
set_bool_default(SDL_LIBTHAI OFF)
set_bool_default(SDL_LIBTHAI_SHARED OFF)
set_bool_default(SDL_WAYLAND ON)
set_bool_default(SDL_WAYLAND_SHARED ON)
set_bool_default(SDL_WAYLAND_LIBDECOR ON)
set_bool_default(SDL_WAYLAND_LIBDECOR_SHARED ON)
set_bool_default(SDL_RPI ON)
set_bool_default(SDL_ROCKCHIP OFF)
set_bool_default(SDL_COCOA ON)
set_bool_default(SDL_DIRECTX ON)
set_bool_default(SDL_XINPUT ON)
set_bool_default(SDL_WASAPI ON)
set_bool_default(SDL_RENDER_D3D OFF)
set_bool_default(SDL_RENDER_D3D11 OFF)
set_bool_default(SDL_RENDER_D3D12 OFF)
set_bool_default(SDL_RENDER_METAL OFF)
set_bool_default(SDL_RENDER_GPU OFF)
set_bool_default(SDL_RENDER_VULKAN OFF)
set_bool_default(SDL_VIVANTE OFF)
set_bool_default(SDL_VULKAN ON)
set_bool_default(SDL_METAL ON)
set_bool_default(SDL_OPENVR ON)
set_bool_default(SDL_KMSDRM OFF)
set_bool_default(SDL_KMSDRM_SHARED OFF)
set_bool_default(SDL_OFFSCREEN ON)
set_bool_default(SDL_HIDAPI_LIBUSB ON)
set_bool_default(SDL_HIDAPI_LIBUSB_SHARED ON)
set_bool_default(SDL_HIDAPI_JOYSTICK ON)
set_bool_default(SDL_VIRTUAL_JOYSTICK OFF)
set_bool_default(SDL_LIBUDEV ON)

add_subdirectory(SDL)

set_bool_default(SDLTTF_VENDORED ON)
set_bool_default(SDLTTF_WERROR OFF)
set_bool_default(SDLTTF_STRICT OFF)
set_bool_default(SDLTTF_HARFBUZZ OFF)
set_bool_default(SDLTTF_PLUTOSVG OFF)
add_subdirectory(SDL_ttf)

set_bool_default(SDLMIXER_VENDORED ON)
set_bool_default(SDLMIXER_WERROR OFF)
set_bool_default(SDLMIXER_STRICT OFF)
set_bool_default(SDLMIXER_DEPS_SHARED ON)
set_bool_default(SDLMIXER_AIFF OFF)
set_bool_default(SDLMIXER_WAVE ON)
set_bool_default(SDLMIXER_VOC OFF)
set_bool_default(SDLMIXER_AU OFF)
set_bool_default(SDLMIXER_FLAC ON)
set_bool_default(SDLMIXER_FLAC_LIBFLAC OFF)
set_bool_default(SDLMIXER_FLAC_LIBFLAC_SHARED OFF)
set_bool_default(SDLMIXER_FLAC_DRFLAC ON)
set_bool_default(SDLMIXER_GME OFF)
set_bool_default(SDLMIXER_GME_SHARED OFF)
set_bool_default(SDLMIXER_MOD OFF)
set_bool_default(SDLMIXER_MOD_XMP OFF)
set_bool_default(SDLMIXER_MOD_XMP_LITE OFF)
set_bool_default(SDLMIXER_MOD_XMP_SHARED OFF)
set_bool_default(SDLMIXER_MP3 ON)
set_bool_default(SDLMIXER_MP3_DRMP3 ON)
set_bool_default(SDLMIXER_MP3_MPG123 OFF)
set_bool_default(SDLMIXER_MP3_MPG123_SHARED OFF)
set_bool_default(SDLMIXER_MIDI ON)
set_bool_default(SDLMIXER_MIDI_FLUIDSYNTH OFF)
set_bool_default(SDLMIXER_MIDI_FLUIDSYNTH_SHARED OFF)
set_bool_default(SDLMIXER_MIDI_TIMIDITY ON)
set_bool_default(SDLMIXER_OPUS ON)
set_bool_default(SDLMIXER_OPUS_SHARED ON)
set_bool_default(SDLMIXER_VORBIS_STB ON)
set_bool_default(SDLMIXER_VORBIS_VORBISFILE ON)
set_bool_default(SDLMIXER_VORBIS_VORBISFILE_SHARED ON)
set_bool_default(SDLMIXER_VORBIS_TREMOR OFF)
set_bool_default(SDLMIXER_VORBIS_TREMOR_SHARED OFF)
set_bool_default(SDLMIXER_WAVPACK OFF)
set_bool_default(SDLMIXER_WAVPACK_DSD OFF)
set_bool_default(SDLMIXER_WAVPACK_SHARED OFF)
add_subdirectory(SDL_mixer)

set_bool_default(SDLIMAGE_VENDORED ON)
set_bool_default(SDLIMAGE_WERROR OFF)
set_bool_default(SDLIMAGE_STRICT OFF)
set_bool_default(SDLIMAGE_DEPS_SHARED ON)
set_bool_default(SDLIMAGE_BACKEND_STB OFF)
set_bool_default(SDLIMAGE_BACKEND_WIC OFF)
set_bool_default(SDLIMAGE_BACKEND_IMAGEIO ON)
set_bool_default(SDLIMAGE_ANI OFF)
set_bool_default(SDLIMAGE_ANI_SAVE OFF)
set_bool_default(SDLIMAGE_AVIF ON)
set_bool_default(SDLIMAGE_AVIF_SAVE ON)
set_bool_default(SDLIMAGE_AVIF_SHARED ON)
set_bool_default(SDLIMAGE_BMP OFF)
set_bool_default(SDLIMAGE_BMP_SAVE OFF)
set_bool_default(SDLIMAGE_GIF OFF)
set_bool_default(SDLIMAGE_GIF_SAVE OFF)
set_bool_default(SDLIMAGE_JPG ON)
set_bool_default(SDLIMAGE_JPG_SAVE OFF)
set_bool_default(SDLIMAGE_JPG_SHARED ON)
set_bool_default(SDLIMAGE_JXL OFF)
set_bool_default(SDLIMAGE_JXL_SHARED OFF)
set_bool_default(SDLIMAGE_LBM OFF)
set_bool_default(SDLIMAGE_PCX OFF)
set_bool_default(SDLIMAGE_PNG ON)
set_bool_default(SDLIMAGE_PNG_LIBPNG ON)
set_bool_default(SDLIMAGE_PNG_SAVE ON)
set_bool_default(SDLIMAGE_PNG_SHARED ON)
set_bool_default(SDLIMAGE_PNM OFF)
set_bool_default(SDLIMAGE_QOI OFF)
set_bool_default(SDLIMAGE_SVG OFF)
set_bool_default(SDLIMAGE_TGA OFF)
set_bool_default(SDLIMAGE_TGA_SAVE OFF)
set_bool_default(SDLIMAGE_TIF ON)
set_bool_default(SDLIMAGE_TIF_SHARED ON)
set_bool_default(SDLIMAGE_WEBP OFF)
set_bool_default(SDLIMAGE_WEBP_SAVE OFF)
set_bool_default(SDLIMAGE_WEBP_SHARED OFF)
set_bool_default(SDLIMAGE_XCF OFF)
set_bool_default(SDLIMAGE_XPM OFF)
set_bool_default(SDLIMAGE_XV OFF)
add_subdirectory(SDL_image)

# # SDL_Image bug: https://github.com/libsdl-org/SDL_image/issues/506
# if (APPLE)
#     find_library(IO_LIB ImageIO REQUIRED)
#     find_library(CS_LIB CoreServices REQUIRED)
#     find_library(CT_LIB CoreText REQUIRED)
#     find_library(CG_LIB CoreGraphics REQUIRED)
#     find_library(CF_LIB CoreFoundation REQUIRED)
# endif()
